window.translated = {
    "Light": "Ánh Sáng",
    "Blademaster": "Kiếm Khách",
    "The Darkin Blade": "",
    "Active": "(Chủ động)",
    "Damage": "Sát thương",
    "250/500/1000": "250/500/1000",
    "Aatrox cleaves the area in front of him, dealing damage to enemies inside it.": "Aatrox đánh vào vùng trước mặt, gây sát thương lên kẻ địch trong nó.",
    "Inferno": "Lửa",
    "Summoner": "Triệu Hồi",
    "Summon Tibbers": "Triệu Hồi Gấu Tibber",
    "Initial Damage": "",
    "100/200/300": "100/200/300",
    "Annie summons Tibbers to fight alongside her dealing damage to enemies in the area.": "Annie triệu hồi gấu Tibbers, gây sát thương cho kẻ địch cạnh bên.",
    "Crystal": "Ngọc",
    "Ranger": "Xạ Thủ",
    "Ranger's Focus": "",
    "Attack Speed Bonus": "Tốc độ đánh cộng thêm",
    "50%/75%/250%": "",
    "For 5 seconds, Ashe gains 50% Attack Speed, and her basic attacks fire a flurry of arrows dealing physical damage.": "Trong 5 giây, Ashe tăng 50% tốc độ đánh, và đòn đánh gây thêm sát thương vật lý.",
    "Desert": "Cát",
    "Arise!": "Trỗi Dậy!",
    "125/250/375": "",
    "Azir summons a Sand Soldier for 6 seconds. Sand Soldiers attack nearby enemies whenever Azir attacks, dealing magic damage in a line.": "Azir triệu hồi 1 chiến bình cát tồn tại trong 6 giây. Chiến binh cát tấn công kẻ địch cạnh bên theo mỗi đòn đánh của Azir, gây sát thương phép trên đường thẳng",
    "Mage": "Pháp sư",
    "Pyroclasm": "Bão Lửa",
    "300/450/600": "",
    "Brand launches a bouncing fireball, damaging enemies hit.": "Brand phóng ra một luồng lửa hủy diệt, gây sát thương phép mỗi lần nó nảy.",
    "Glacial": "Băng Quốc",
    "Warden": "Hộ vệ",
    "Unbreakable": "Tối Kiên Cường",
    "Damage Reduction": "Giảm sát thương",
    "70%/80%/90%": "",
    "Braum gains a barrier that reduces incoming damage.": "Braum giương khiên lên và giảm sát thương nhận vào",
    "Assassin": "Sát Thủ",
    "Flame Cascade": "Thác Bạc",
    "80/100/120": "",
    "Diana creates orbs that spin around her and explode upon contact with an enemy, dealing magic damage. Additionally, Diane gains a shield for 3 seconds.": "Diana tạo ra ba quả cầu bay quanh người, chúng sẽ phát nổ khi tiếp xúc với kẻ địch gây sát thương trên khu vực. Cô cũng được nhận một lớp giáp chặn sát thương trong 3 giây",
    "Poison": "Độc",
    "Berserker": "Cuồng Chiến",
    "Adrenaline Rush": "Máu Điên",
    "50/100/150": "",
    "Dr Mundo creates a toxic cloud around him that deals damage to nearby enemies and heals for a portion of the damage every second for 8 seconds.": "Dr Mundo tạo 1 vùng khói độc gây sát thương xung quanh và hồi 1 phần sát thương nhận phải trong 8 giây.",
    "Ice Shot": "",
    "200/400/800": "",
    "Ezreal fires a shard of ice at the lowest HP unit, dealing magic damage and applying on-hit effects.": "Ezreal bắn ra 1 mảnh băng vào mục tiêu ít máu nhất, gây sát thương phép và hiệu ứng đòn đánh.",
    "Woodland": "Rừng",
    "Druid": "Tự nhiên",
    "Triggerseed": "Hạt Hư Hỏng",
    "Shield Amount": "Lượng giáp",
    "200/350/500": "",
    "Ivern shields the ally with the lowest health for 5 seconds.": "Ivern tạo 1 lớp giáp cho đồi độc ít máu nhất trong 5 giây.",
    "Cloud": "Gió",
    "Mystic": "Bí ẩn",
    "Monsoon": "Gió Mùa",
    "Heal Amount": "Lượng máu hồi",
    "20%/30%/100%": "",
    "Janna channels winds which heal allies based on their maximum health and stun nearby enemies for 1 second.": "Janna tạo 1 vùng gió hồi máu cho đồng đội theo số máu tối đa và làm choáng kẻ địch cạnh bên trong 1 giây.",
    "Counter Strike": "Phản Đòn",
    "150/250/450": "",
    "Jax dodges all incoming attacks for 2 seconds, then strikes nearby enemies, stunning them for 1.5 seconds.": "Jax né mọi đòn đánh trong 2 giây, sau đó phản đòn, làm choáng kẻ địch cạnh bên trong 1.5 giây.",
    "Void Assault": "Đột Kích Hư Không",
    "Bonus Damage": "Sát Thương Cộng Thêm",
    "100/200/500": "",
    "Kha'Zix goes stealth and attacks the enemy with the lowest health after a short delay. This attack is a critical hit and restores mana.": "Kha'Zix tàng hình và tấn công kẻ địch thấp máu nhất ",
    "Shadow": "Bóng tối",
    "Dance of Dread": "",
    "150/325/650": "",
    "Wolf mauls Kindred's target, dealing magic damage and reducing healing by 80% to her target for 5 seconds, while Lamb leaps away from Kindred's target.": "Sói cắn vào mục tiêu của Kindred, gây sát thương phép và giảm 80% hồi máu trong 5 giây, cùng lúc cừu nhảy ra xa khỏi mục tiêu.",
    "Predator": "Mãnh thú",
    "Living Artillery": "Pháo Sinh Học",
    "125/275/425": "",
    "Kog'Maw fires a living artillery shell at a random enemy, dealing damage.": "Kog'Maw bắn ra đạn sinh học vào kẻ địch ngẫu nhiên, gây sát thương phép.",
    "Ethereal Chains": "Sợi Xích Siêu Phàm",
    "200/450/800": "",
    "Leblanc flings an illusory chain toward a random enemy, dealing damage and stunning them after 1.5 seconds.": "LeBlanc bắn ra 1 sợi xích ảo thuật vào mục tiêu ngẫu nhiên, gây sát thương và choáng chúng trong 1.5 giây.",
    "Avatar": "Hóa thân",
    "Final Spark": "Cầu Vồng Tối Thượng",
    "500/800/9999": "",
    "Lux fires a straight beam of light at enemies. If at least one enemy is killed, she restores 50 mana.": "Lux bắn một dải sáng gây sát thương lên tất cả mục tiêu trong vùng ảnh hưởng. Nếu có ít nhất 1 mục tiêu bị tiêu diệt, cô hồi lại 50 mana.",
    "Electric": "Sét",
    "Ocean": "Nước",
    "Steel": "Thép",
    "Mountain": "Đất",
    "Unstoppable Force": "Không Thể Cản Phá",
    "125/200/275": "",
    "Malphite charges toward a random enemy, dealing damage and knocking all nearby enemies into the air and stunning them.": "Malphite tông vào kẻ địch ngẫu nhiên, gây sát thương và hất tung chúng và làm choáng.",
    "Shadow Swarm": "Bầy Bọ Hư Không",
    "Number of Spirits": "Số tinh linh",
    "2/3/4": "",
    "Malzahar creates a shadow portal, summoning Shadow Spawns. The Shadow Spawns hit for magic damage each attack. Shadow Spawn benefit from active Shadow trait bonuses.": "Malzahar tạo 1 cổng bóng tối, triệu hồi ra bọ hư không. Đòn đánh của bọ gây sát thương phép. Bọ nhận hiệu ứng từ thuộc tính Bóng tối.",
    "Sap Magic": "Ma Pháp Nhựa Cây",
    "Passive": "(Nội tại)",
    "After taking damage from a spell, Maokai's next attack will heal him.": "Sau khi nhận sát thương từ một phép, đòn đánh kế tiếp sẽ hồi máu cho Maokai.",
    "Meditate": "Thiền",
    "50/75/500": "",
    "Master Yi meditates, becoming untargetable for 1 second and healing over the duration. After Master Yi finishes meditating, he gains 100% Attack Speed and deal bonus magic damage on hit for 6 seconds.": "Master Yi thiền, trở nên không thể chỉ định trong 1 giây và hồi máu. Sau đó tăng 100% tốc độ đánh vào gây thêm sát thương phép mỗi đòn đánh trong 6 giây.",
    "Tidal Wave": "Đại hồng thủy",
    "150/250/350": "",
    "Nami sends a massive wave toward a random enemy, damaging and knocking up enemies it passes through and granting allies it passes through bonus magic damage on hit.": "Nami tạo một cơn Sóng thần vào kẻ địch ngẫu nhiên, gây sát thương và hất tung chúng và tăng thêm sát thương phép mỗi đòn đánh cho đồng mình trong vùng ảnh hưởng. ",
    "Fury of the Dawn": "Cơn Thịnh Nộ Ánh Sáng",
    "50/70/90": "",
    "Nasus surrounds himself with light for 7 seconds, gaining bonus health and damaging adjacent enemies each second.": "Nasus bao bọc bản thân bằng ánh sáng trong 7 giây, tăng thêm máu và gây sát thương lên kẻ địch cạnh bên mỗi giây.",
    "Depth Charge": "Thủy Lôi Tầm Nhiệt",
    "100/200/400": "",
    "Nautilus sends out a depth charge that seeks out the furthest enemy champion, knocking them up and stunning them. It also deals damage to all enemies it passes.": "Nautilus bắn ra một cơn sóng chấn động xuống mặt đất đuổi theo kẻ địch xa nhất, hất tung và làm choáng chúng. Ngoài ra nó còn gây sát thương lên những mục tiêu trong phạm vi.",
    "Blooming Burst": "",
    "100/200/350": "",
    "Neeko throws a seed at a random target, exploding three times with increasing radius, dealing damage to all enemies hit by each explosion.": "Neeko ném ra 1 hạt giống vào kẻ địch ngẫu nhiên, gây nổ 3 lần với phạm vi tăng dần, gây sát thương lên tất cả kẻ địch bị ảnh hưởng.",
    "Steel Blades": "Gươm Thép",
    "40%/60%/80%": "",
    "Every third attack, Nocturne deals additional damage to enemies around him and heals for a portion of the damage.": "Nocturne gây thêm sát thương lên kẻ địch xung quanh và hồi máu mỗi 3 đòn đánh",
    "Ragnarok": "Tận Thế Ragnarok",
    "100%/150%/300%": "",
    "Olaf gains attack speed, lifesteal based on missing health, and immunity to crowd control for the rest of combat.": "Olaf tăng tốc độ đánh, hút máu theo lượng máu đã mất, và miễn nhiễm với hiệu ứng khống chế cho đến hết trận.",
    "Lightning Breath": "Hơi Thở Sấm Sét",
    "Ornn unleashes lightning bolts in a cone in front of him, dealing damage and increasing their chance to be critical struck by 20% for 4 seconds.": "Ornn gây sát thương 1 vùng trước mặt và tăng 20% khả năng bị chí mạng của mục tiêu bị ảnh hưởng trong 4 giây.",
    "Edge of Ixtal": "",
    "300/500/700": "",
    "Qiyana dashes to the side of her target and throws a blast of wind through them, damaging and stunning enemies it passes through. Qiyana's element will change every match between Woodland, Inferno, Ocean, and Cloud.": "Qiyana lướt đến cạnh mục tiêu và 1 luồng gió qua chúng, gây sát thương và làm choáng chúng. Nguyên tố của Qiyana sẽ thay đổi theo mỗi trận.",
    "Furious Bite": "",
    "250/550/850": "",
    "Rek'Sai bites an enemy dealing true damage.": "Rek'Sai cắn vào mục tiêu và gây sát thương chuẩn.",
    "Cull the Meek": "Vũ Điệu Cá Sấu",
    "150/275/400": "",
    "Renekton swings his blade, dealing damage to nearby enemies and restoring health.": "Renekton quơ đao, gây sát thương lên kẻ địch cạnh bên và hồi máu.",
    "Alchemist": "Giả Kim",
    "Poison Trail": "Phun Khói Độc",
    "200/400/2000": "",
    "Singed leaves a poison cloud behind him damaging enemies in the area over 4 seconds.": "Singed để lại 1 làn khói độc sau lưng, gây sát thương trong 4 giây.",
    "Decimating Smash": "Cú Nện Tàn Khốc",
    "Sion smashes his axe into the ground after a short delay, dealing damage and knocking up enemies in the area.": "Sion nện rìu xuống đất sau khi niệm, gây sát thương và hất tung kẻ địch trong vùng.",
    "Ricochet": "Nảy Bật",
    "100%/125%/150%": "",
    "For the next 5 seconds, Sivir's attacks will bounce up to 10 times to nearby enemies, dealing damage and applying on-hit effects.": "Trong 5 giây, đòn đánh của Sivir sẽ nảy đến 10 lần vào các mục tiêu cạnh bên, gây sát thương và hiệu ứng đòn đánh.",
    "Crystalline Exoskeleton": "Lớp Vỏ Tinh Thể",
    "150/450/750": "",
    "Skarner is shielded for 8 seconds. While the shield persists, Skarner gains attack speed.": "Skarner tạo lá chắn trong 8 giây, tăng tốc độ đánh khi còn lá chắn.",
    "Equinox": "Điểm Phân Cực",
    "150/300/450": "",
    "Soraka creates a zone at a random enemy's location, dealing magic damage and preventing mana from being restored to enemies inside.": "Soraka tạo 1 vùng vào mục tiêu ngẫu nhiên, gây sát thương phép và ngăn chúng hồi mana.",
    "Hydro Sphere": "Cầu Nước",
    "175/350/600": "",
    "Syndra conjures a sphere of water near a random enemy which explodes dealing magic damage to all enemies hit.": "Syndra tạo 1 cầu nước cạnh mục tiêu ngẫu nhiên và gây sát thương phép lên chúng.",
    "Seismic Shove": "Quăng Địa Chấn",
    "150/350/550": "",
    "Taliyah causes the ground to rise under the enemy with the most Mana, dealing damage and either pushing or pulling them toward her.": "Taliyah khiến một khu vực trồi lên dưới kẻ địch có nhiều mana nhất, gây sát thương và ném hoặc đẩy chúng đi.",
    "Cosmic Radiance": "Vũ Trụ Rạng Ngời",
    "Duration": "Thời lượng",
    "3/3/5": "",
    "After a delay, Taric and all nearby allies become invulnerable.": "Sau khi niệm, Taric và tất cả đồng minh xung quanh được miễn nhiễm sát thương.",
    "Deep Sea Lantern": "Lồng Đèn",
    "250/400/600": "",
    "Thresh throws his lantern to the lowest-health ally, shielding them and nearby allies for 5 seconds.": "Thresh ném lồng đèn vào đồng minh ít máu nhất, tạo lá chắn cho chúng trong 5 giây.",
    "Spray and Pray": "Nhắm Mắt Bắn Bừa",
    "125%/150%/200%": "",
    "Twitch gains increased damage and unlimited range for 8 seconds.": "Twitch tăng sát thương và vô hạn tầm đánh trong 8 giây.",
    "Piercing Arrow": "Mũi Tên Xuyên Phá",
    "225/450/675": "",
    "Varus charges for 1.5 seconds and fires an arrow, dealing damage to all enemies in a line.": "Varus kéo cung trong 1.5 giây và bắn ra 1 mũi tên, gây sát thương vào mọi kẻ địch trên đường thẳng.",
    "Silver Bolts": "Mũi Tên Bạc",
    "9%/12%/15%": "",
    "Vayne deals bonus true damage every third attack based on the enemy's maximum health.": "Vayne gây thêm sát thương chuẩn mỗi 3 đòn đánh dựa trên số máu tối đa của mục tiêu.",
    "Primordial Burst": "Vụ Nổ Vũ Trụ",
    "300/600/900": "",
    "Veigar blasts an enemy with magical energy, dealing damage. This spell instantly kills if the enemy is a lower star level than Veigar.": "Veigar phóng chưởng vào tướng địch, gây lượng sát thương phép. Kĩ năng này sẽ tiêu diệt ngay lập tực mục tiêu có số sao thấp hơn Veigar.",
    "Drain": "Hút",
    "200/325/450": "",
    "Vladimir damages a target enemy, healing himself for the damage dealt.": "Vladimir gây sát thương và hồi máu.",
    "Frenzied Bite": "",
    "200/450/850": "",
    "Volibear bites an enemy. If the target has less than 35% health, it is killed instantly and Volibear fully restores his mana.": "Volibear cắn kẻ địch. Tiêu diệt ngay lập tức mục tiêu dưới 35% máu và hồi lại đầy mana.",
    "Infinite Duress": "Khóa Chết",
    "150/225/300": "",
    "Warwick pounces onto the lowest health enemy, stunning, damaging, and applying on-hit effects while healing himself.": "Warwick vồ vào mục tiêu thấp máu nhất, làm choáng, gây sát thương và áp dụng hiệu ứng đòn đánh đồng thời hồi máu.",
    "Last Breath": "Trăn Trối",
    "Hits": "Đòn",
    "4/5/6": "",
    "Yasuo blinks to the enemy with the most items and knocks them up, holding them airborn for 1 second and hitting them, dealing basic attack damage and applying on-hit effects.": "Yasuo biến đến kẻ địch có nhiều đồ nhất và hất tung chúng, giữ chúng trên không trong 1 giây và gây sát thương có áp dụng hiệu ứng đòn đánh",
    "Shepherd of Souls": "",
    "Number of Allies": "Số đồng minh",
    "2/3/12": "",
    "Yorick blesses his allies with the lowest health, not including Light Walkers. When they die, they resurect as Light Walkers and benefits from the effects of the Light origin.": "Yorick niệm lên đồng minh có ít máu nhất, không bao gồm tướng Ánh Sáng. Hồi sinh thành Tinh Linh Ánh Sáng và hưởng lợi từ hiệu của của tộc Ánh sáng khi chúng chết.",
    "Living Shadow": "Phân Thân Bóng Tối",
    "Mana Cost Increase": "Lượng mana tiêu thụ",
    "50/25/0": "",
    "Zed creates a clone of himself behind his current target. This clone inherits its creator's items, stats, and current health, and can cast Living Shadow. Its mana cost is 50 higher.": "Zed tạo phân thân ra sau mục tiêu. Phân thân có cùng trang bị, chỉ số, máu với chủ thể và có thể tự tạo phân thân nhưng lượng mana tiêu thụ sẽ tăng 50.",
    "Rampant Growth": "Xum Xuê",
    "70/80/90": "",
    "Zyra summons two Flame Spitters at a random location at the edge of the arena. The Flame Spitters attack the nearest enemy for 3 seconds, dealing damage per attack a total of 4 times.": "Zyra triệu hồi Cây Phun Gai tại vị trí ngẫu nhiên. Cây Phun Gai tấn công mục tiêu gần nhất trong 3 giây, gây sát thương mỗi đòn đánh 4 lần.",
    "Cloud Blademasters": "Kiếm Khách Gió",
    "Hush": "Dao Câm Lặng",
    "Basic Attacks have a 33% chance to silence the target on-hit, prevent the enemy from gaining mana for 4 seconds.": "Đòn đánh thường có 33% tỉ lệ làm mục tiêu bị câm lặng, ngăn hồi mana trong 4 giây.",
    "Runaan's Hurricane": "Cuồng Cung Runaan",
    "Basic Attacks fire an additional missile at another nearby enemy, dealing 60% of the wearer's Attack damage and applying on-hit effects.": "Đòn đánh thường bắn thêm 1 tên lửa vào mục tiêu khác, gây 60% sát thương và áp dụng hiệu ứng.",
    "Sword Breaker": "Phá Kiếm",
    "Wearer's Basic Attacks have a 33% chance to disarm the target for 3 seconds, preventing that enemy from Basic Attacking.": "Đòn đánh thường có 33% tỉ lệ giải giới mục tiêu trong 3 giây, ngăn cản chúng đánh thường.",
    "Blade of the Ruined King": "Gươm Của Vua Vô Danh",
    "Wearer is also a Blademaster.": "Chủ sở hữu đồng thời là Kiếm Khách",
    "Bloodthirster": "Huyết Kiếm",
    "Basic Attacks heal the wearer for 40% of the damage dealt.": "Đòn đánh hồi lại 40% sát thương gây ra.",
    "Infinity Edge": "Vô Cực Kiếm",
    "The wearer gains +125% Critical Strike Damage.": "Chủ sở hữu tăng 125% Sát thương chí mạng.",
    "Blademaster Basic Attacks have a 40% chance to trigger additional attacks against their target. These additional attacks deal damage like Basic Attacks and trigger on-hit effects.": "Đòn đánh thường của Kiếm Khách có 40% tỉ lệ đánh thêm. Đòn đánh thêm có sát thương và hiệu ứng như đánh thường.",
    "1 Extra Attack": "1 Đòn Đánh Thêm",
    "2 Extra Attacks": "2 Đòn Đánh Thêm",
    "3 Extra Attacks": "3 Đòn Đánh Thêm",
    "All allies gain dodge chance.": "Đồng mình tăng tỉ lệ né đòn.",
    "+15% Dodge Chance": "+15% Tỉ Lệ Né",
    "+20% Dodge Chance": "+20% Tỉ Lệ Né",
    "+30% Dodge Chance": "+30% Tỉ Lệ Né",
    "Innate: At the start of combat, Assassins leap to the farthest enemy. Assassins gain bonus Critical Strike Damage and Chance.": "Nội tại: Sát Thủ nhảy với mục tiêu xa nhất. Sát thủ tăng thêm Sát thương Chí Mạng và tỉ lệ Chí Mạng.",
    "+75% Critical Strike Damage & 10% Critical Strike Chance": "+75% Sát thương Chí Mạng và 10% tỉ lệ Chí Mạng",
    "+150% Critical Strike Damage & 20% Critical Strike Chance": "+150% Sát thương Chí Mạng và 10% tỉ lệ Chí Mạng",
    "Reduces each enemy's armor.": "Giảm Giáp mỗi kẻ địch.",
    "50% Armor Reduction": " 50% Giảm Giáp",
    "90% Armor Reduction": "90% Giảm Giáp",
    "All allies gain increased Magic Resistance.": "Tất cả đồng mình được tăng Kháng Phép.",
    "40 Magic Resistance": "40 Kháng Phép",
    "120 Magic Resistance": "120 Khàng Phép",
    "Poison Glacial": "Độc Băng Quốc",
    "Luden's Echo": "Vọng Âm Luden",
    "When the wearer deals damage with their spell, the first target hit and up to 3 nearby enemies are dealt an additional 180 magic damage.": "Kỹ năng gây 180 sát thương phép vào 3 mục tiêu cạnh bên.",
    "Guinsoo's Rageblade": "Cuồng Đao Guinsoo",
    "Basic Attacks grant the wearer +4% bonus Attack Speed for the rest of combat. This effect can stack any number of times.": "Đòn đánh thường tăng 4% Tốc Độ Đánh cho đến hết trận. Cộng dồn vô hạn.",
    "Frozen Mallet": "Búa Băng",
    "Wearer is also a Glacial.": "Chủ sở hữu đồng thời là Băng Quốc/",
    "Morellonomicon": "Quỷ thư Morello",
    "When the wearer deals damage with their spell, they burn the target, dealing 20% of the target's Maximum Health as true damage over 10 seconds and reducing healing by 80% for the duration of the burn. A champion can only have one burn effect at a time, preferring the strongest.": "Kỹ năng thiêu đốt 20% máu tối đa trong 10 giây và giảm 80% khả năng hồi máu của mục tiêu.",
    "Basic Attacks from Glacials have a chance to stun their target for 1.5 seconds.": "Đòn đánh từ Băng Quốc có tỉ lệ làm chóng mục tiêu trong 1.5 giây.",
    "20% Chance to Stun": "20% Tỉ lệ choáng",
    "35% Chance to Stun": "35% Tỉ lệ choáng",
    "50% Chance to Stun": "50% Tỉ lệ choáng",
    "undefined": "",
    "Poison champions apply Neurotoxin when they deal damage, increasing the target's mana cost by 50%.": "Tướng Độc nhiễm độc kẻ địch khi gây sát thương, tăng lượng mana tiêu tốn lên 50%.",
    "Innate: Alchemists ignore collision and never stop moving.": "Nội tại: Giả Kim vượt mọi địa hình và không dừng di chuyển.",
    "Innate: At the start of combat, Berserkers leap to the nearest enemy. Berserkers have a 40% chance to hit all units in a cone in front of them with their attacks.": "Nội tại: Khi bắt đầu trận, Cuồng Chiến nhảy vào kẻ địch gần nhất. Cuồng Chiến có 40% tỉ lệ đánh lan.",
    "40% Chance": "40% Tỉ lệ",
    "100% Chance": "100% Tỉ lệ",
    "Every 3 seconds, Rangers have a chance to double their Attack Speed for 3 seconds.": "Mỗi 3 giây, Xạ Thủ có khả năng được nhân đôi Tốc Độ Đánh trong 3 giây.",
    "30% Chance to Double Attack Speed": "30% Nhân đôi Tốc Độ Đánh",
    "60% Chance to Double Attack Speed": "60% Nhân đôi Tốc Độ Đánh",
    "100% Chance to Double Attack Speed": "100% Nhân đôi Tốc Độ Đánh",
    "Shadow Summoners": "Bóng Tối Triệu Hồi",
    "Spear of Shojin": "Ngọn Giáo Shojin",
    "After casting their spell, the wearer's Basic Attacks restore 18% of their Maximum Mana.": "Đòn đánh hồi 18% mana sau khi dùng kỹ năng.",
    "Phantom Dancer": "Ma Vũ Song Kiếm",
    "Wearer dodges all Critical Strikes.": "Chủ sở hữu né tất cả đòn Chí Mạng.",
    "Seraph's Embrace": "Quyền Trượng Đại Thiên Sứ",
    "After casting their spell, the wearer restores 20 Mana.": "Hồi 20 mana sau khi sử dụng kỹ năng.",
    "Shadow units deal increased damage for 5 seconds at combat start, refreshed on takedown.": "Tướng Bóng Tối gây thêm sát thương trong 5 giây khi bắt đầu giao tranh và sau mỗi hạ gục.",
    "+45% Increased Damage, Self Takedown": "+45% Tăng Sát Thương, tự hạ gục",
    "+85% Increased Damage, Any Shadow Takedown": "+85% Tăng Sát Thương, tự hạ gục",
    "Summoned units have increased health and duration.": "Mục tiêu được triệu hồi đc tăng máu và thời gian.",
    "+40% increase": "Tăng 40%",
    "+100% increase": "Tăng 100%",
    "Inferno spell damage burns the ground beneath the target, dealing a percent of that spell's pre-mitigation damage as magic damage over 5 seconds.": "Kỹ năng lửa thiêu đốt mặt đất dưới chân mục tiêu, gây sát thương theo kỹ năng trong 5 giây.",
    "+80% Damage": "80% Sát thương",
    "+175% Damage": "+175% Sát thương",
    "+275% Damage": "+275% Sát thương",
    "Ocean Mages": "Pháp Sư Nước",
    "Mage's Cap": "Mũ Pháp Sư",
    "Wearer is also a Mage.": "Chủ sở hữu đồng thời là Pháp Sư.",
    "Rabadon's Deathcap": "Mũ Tử Thần Rabadon",
    "Wearer gains +50% Spell Power Amplification. (All sources of Spell Power are 50% more effective)": "Chủ sở hữu tăng 50% Sát thương phép.",
    "All allies restore mana every 4 seconds.": "Tất cả đồng mình hồi mana mỗi 4 giây.",
    "+15 Mana": "+15 Mana",
    "+35 Mana": "+35 Mana",
    "+60 Mana": "+60 Mana",
    "Mages have a chance on cast to instead Doublecast.": "Pháp Sư có tỉ lệ dùng kỹ năng thêm 1 lần.",
    "50% Chance": "50% Tỉ lệ",
    "Wardens gain increased total Armor.": "Hộ Vệ tăng giáp tối đa.",
    "+150% Armor": "+150% Giáp",
    "+300% Armor": "+300% Giáp",
    "+450% Armor": "+450% Giáp",
    "Hyper Roll Light": "Hyper Roll Ánh Sáng",
    "Giant Slayer": "Diệt Khổng Lồ",
    "The wearer's basic attacks deal an additional 5% of the target's Maximum Health as true damage.": "Đòn đánh gây thêm sát thương chuẩn bằng 5% Máu tối đa.",
    "Talisman of Light": "Bùa Ánh Sáng",
    "Wearer is also a Light.": "Chủ sở hữu đồng thời là Ánh Sáng.",
    "Guardian Angel": "Giáp Thiên Thần",
    "When the wearer dies, they cleanse negative effects and revive with up to 500 Health after a 2 second delay. This effect can trigger once per combat.": "Hồi sinh với 500 Máu sau 2 giây sau khi bị hạ gục. Hiệu ứng chỉ kích hoạt 1 lần mỗi giao tranh.",
    "Hextech Gunblade": "Kiếm Súng Hextech",
    "Basic Attacks and spells heal the wearer for 25% of the damage dealt.": "Đòn đánh thường và kỹ năng hồi máu bằng 25% sát thương gây ra.",
    "When a Light champion dies, all other Light champions gain Attack Speed and are healed for 25% of the champion's Maximum Health.": "Khi tướng Ánh Sáng bị hạ gục, toàn bộ tướng Ánh Sáng khác được tăng Tốc Độ Đánh và hồi 25% Máu tối đa.",
    "+10% Attack Speed": "+10% Tốc Độ Đánh",
    "+20% Attack Speed": "+20% Tốc Độ Đánh",
    "+35% Attack Speed": "+35% Tốc Độ Đánh",
    "Steel Assassins": "Sát Thủ Thép",
    "Youmuu's Ghostblade": "Kiếm Ma Youmuu",
    "Wearer is also an Assassin.": "Chủ sở hữu đồng thời là Sát thủ.",
    "Steel champions gain damage immunity for a few seconds when they are reduced below 50% health.": "Tướng Thép được miễn nhiễm sát thương vài giây sau khi máu dưới 50%.",
    "2 Seconds of Immunity": "2 Giây Miễn Nhiễm",
    "3 Seconds of Immunity": "3 Giây Miễn Nhiễm",
    "4 Seconds of Immunity": "4 Giây Miễn Nhiễm",
    "Berserkers": "Cuồng Chiến",
    "Berserker Axe": "Rìu Cuồng Chiến",
    "Wearer is also a Berserker.": "Chủ sở hữu đồng thời là Cuồng Chiến.",
    "Hand of Justice": "Bàn Tay Công Lý",
    "At the beginning of each planning phase, the wearer gains one of the following: Basic Attacks and Spells deal +50% Damage or Basic Attacks heal 50 Health on-hit.": "Đầu mỗi giao tranh, chủ sở hữu Tăng 50% sát thương đòn đánh và kỹ năng hoặc Hồi 50 Máu mỗi đòn đánh.",
    "Light Summoners": "Triệu Hồi Ánh Sáng",
    "Red Buff": "Bùa Đỏ",
    "Wearer's Basic Attacks burn the target on-hit, dealing 20% of the target's Maximum Health as true damage over 10 seconds and reducing healing by 80% for the duration of the burn. A champion can only have one burn effect at a time, preferring the strongest.": "Đòn đánh thiêu đốt mục tiêu, gây sát thương chuẩn bằng 20% Máu tối đa của mục tiêu trong 10 giây và giảm 80% hồi máu. Mỗi tướng chỉ có 1 trang bị thiêu đốt.",
    "Ionic Spark": "Nỏ Sét",
    "Whenever an enemy casts a spell, the wearer deals 125 true damage to the caster.": "Gây 125 sát thương chuẩn mỗi khi kẻ địch dùng kỹ năng.",
    "Shadow Blademasters": "Kiếm Khách Bóng Tối",
    "Deathblade": "",
    "Whenever the wearer kills or participates in killing an enemy, gain +15 Attack Damage for the remainder of combat. This effect can stack any number of times.": "Tăng +15 ATK mỗi điểm hạ gục hoặc hỗ trợ. Cộng dồn vô hạn.",
    "Hyper Roll Predators": "Hyper Roll Mãnh Thú",
    "Statikk Shiv": "Dao Điện Statikk",
    "Every third Basic Attack from the wearer deals 100 magical damage to 3 enemies.": "Mỗi 3 đòn đánh gây 100 sát thương phép lên 3 mục tiêu.",
    "Iceborne Gauntlet": "Găng Tay Băng Giá",
    "When the wearer dodges, they create a zone of ice. Enemies inside the zone have their Attack Speed reduced by 35%.": "Mỗi khi né, tạo 1 vùng băng xung quanh. Kẻ địch bị ảnh hưởng giảm 35% Tốc Độ Đánh",
    "Predators instantly kill enemies they damage who are below 25% health.": "Mãnh Thú lập tức tiêu diệt mục tiêu dưới 25% Máu.",
    "Mage Summoners": "Pháp Sư Triệu Hồi",
    "Rangers": "Xạ Thủ",
    "Inferno Cinder": "",
    "Wearer is also an Inferno.": "Chủ sở hữu đồng thời là Lửa.",
    "Crystal champions have a maximum amount of damage they can take from a single hit.": "Tướng Ngọc nhận sát thương tối đa mỗi đòn.",
    "100 Max Damage": "100 Sát thương tối đa",
    "60 Max Damage": "60 Sát thương tối đa",
    "An Avatar's Origin Element is counted twice for Trait bonuses.": "Hóa Thân tính là 2 với mỗi nguyên tố.",
    "Warden Rangers": "Hộ Vệ Xạ Thủ",
    "Inferno Mages": "Pháp Sư Lửa",
    "Poison Inferno": "Độc Lửa",
    "Warmog's Armor": "Giáp Máu Warmog",
    "Wearer regenerates 6% of their missing Health per second.": "Hồi 6% Máu đã mất mỗi giây.",
    "Desert Blademasters": "Kiếm Khách Cát",
    "Shadow Mages": "Pháp Sư Bóng Tối",
    "Hyper Roll Woodland": "Hyper Roll Rừng",
    "At the start of combat, a random Woodland champion makes a copy of themselves.": "Một tướng Rừng ngẫu nhiên được nhân bản khi bắt đồi giao tranh.",
    "Druids regenerate 40 health each second.": "Tự Nhiên hồi 40 Máu mỗi giây.",
    "Blademaster Assassins": "Kiếm Khách Sát Thủ",
    "Jeweled Gauntlet": "Găng Đá Quý",
    "The wearer's spells can critically strike.": "Kỹ năng của chủ sở hữu có thể chí mạng.",
    "Dragon's Claw": "Vuốt Rồng",
    "Wearer gains 50% resistance to magic damage.": "Chủ sở hữu tăng 50% kháng phép.",
    "250/325/400": "",
    "Electric Warden": "Sét Hộ Vệ",
    "At the start of combat, a random ally gains a 1500 Stoneshield.": "Một đồng minh ngẫu nhiên nhận 1500 Lá Chắn khi bắt đầu giao tranh.",
    "Electric champions shock nearby enemies whenever they deal or receive a critical strike.": "Tướng Sét giật kẻ địch cạnh bên mỗi khi nhận hoặc gây Chí Mạng.",
    "70 Damage": "70 Sát Thương",
    "250 Damage": "250 Sát Thương",
    "500 Damage": "500 Sát Thương",
    "Electric Assassins": "Sét Sát Thủ",
    "Glacial Berserkers": "Băng Quốc Cuồng Chiến",
    "Poison Electric": "Độc Sét",
    "Frozen Heart": "Tim Băng",
    "Reduce the Attack Speed of adjacent enemies by 35% for 1 second.": "Giảm Tốc Độ Đánh của kẻ địch cạnh bên 35% trong 1 giây."
}
